### ISSUE TITLE
IndexError: Layer [ATT_Hdr] not found

### ISSUE THREAD

**Issue by byte-arts** [RCayre/mirage#14]
Hi,
first thank you for the fast merging.
I recognized a small problem with the current master branch. Line 863 and 1241 in ble.py are missing the check if the ATT_Hdr exists in the packet.
>ATT_Hdr in packet

Therefore if the processed packet is not from the Atribute protocol the program crash with the following exception:
>Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/dist-packages/mirage-1.1-py3.8.egg/mirage/libs/wireless_utils/packetQueue.py", line 19, in run
    self._target(*(self._args))
  File "/usr/local/lib/python3.8/dist-packages/mirage-1.1-py3.8.egg/mirage/libs/wireless.py", line 206, in _task
    self._add(pkt)
  File "/usr/local/lib/python3.8/dist-packages/mirage-1.1-py3.8.egg/mirage/libs/wireless.py", line 185, in _add
    packet = self.convert(data)
  File "/usr/local/lib/python3.8/dist-packages/mirage-1.1-py3.8.egg/mirage/libs/ble.py", line 863, in convert
    elif packet[ATT_Hdr].opcode == 0xb:
  File "/usr/local/lib/python3.8/dist-packages/scapy-2.4.4-py3.8.egg/scapy/packet.py", line 1185, in __getitem__
    raise IndexError("Layer [%s] not found" % lname)
IndexError: Layer [ATT_Hdr] not found

Best Regards

**Comment by RCayre** [comment]
Hello, 
thank you very much ! I added a patch yesterday to fix a bug, and missed this consequence. It should be fixed now.

**Comment by byte-arts** [comment]
Fixed
