### ISSUE TITLE
loadModule issue

### ISSUE THREAD

**Issue by tlechien** [RCayre/mirage#24]
Hello,

Great repo,

I encounter an issue when trying to load a module:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/mirage-1.1-py3.7.egg/mirage/libs/utils.py", line 230, in loadModule
    return app.App.Instance.loader.load(name)
AttributeError: 'NoneType' object has no attribute 'loader'
```
Following the breadcrumbs I found out that there is an issue in the loader:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'mirage.modules' has no attribute '__modules__'
```

Cordially,

tlechien

**Comment by RCayre** [comment]
Hi, 
weird issue... can you provide me more details ? How are you running Mirage ? sudo ./mirage_launcher ? sudo mirage ?  Are you trying to run a module directly from an external python script ? 
Can you provide me a code snippet allowing to reproduce the issue ? 
Thanks.

**Comment by tlechien** [comment]
Hello,
I admit I could have been clearer.
I'm importing Mirage as a library. Tried both to call loadModule as a standalone function and in a new module. It seems there is sth going on with the loader and the paths ( generated in modules/__init__.py & libs/utils.py).
I modified __init__ in mirage/core/loader.py with
```Python
                self.modulesList = {}
                modulesPath = next(iter(modules.__path__))
                mList = modules.generateModulesDictionary(modulesPath, modulesPath)
                for moduleName,module in mList.items():
                        current = module#__import__("modules."+module, fromlist=module)
                        moduleClass = getattr(current,moduleName)
                        self.modulesList[moduleName] = moduleClass
```
  to fix it (and it works as long as i initialize app.App() beforehand) but it's more of a bandaid than an actual fix.

Cordially,

tlechien
